### ISSUE TITLE
Expand the current binary-state-only validity of fields

### ISSUE THREAD

**Issue by alexandernst** [emolifeconnect/react-form-state-manager#12]
There is a `setValidity` method which accepts a boolean value (I guess `true` for "valid" and `false` for invalid). 
Can you consider expanding this in order to allow more states? There are quite some cases in which I'd like to warn the user about the value of a field not matching my patterns, but not being invalid either ("hey, that doesn't look like a valid phone number, but if you're sure, go on and submit it"). 

Said with other words, there are some situations in which I'd like to let the user submit the form even if the values don't match my validation rules, but I'd like to be able to "retrieve" the fields that don't match my validation rules and warn the user about them.

I guess one way to implement this could be to change `setValidity()` to be able to accept a `state<integer>` instead of `<boolean>`, then define 

```
const STATES = [
    INVALID: 0,
    VALID: 1,
    WARNING: 2,
    // this allows for infinite states
];
```

Then `isValid()` could return `true` (or `1`) if the state is `VALID` or, if the state isn't valid, return the state code.

What do you think?

**Comment by alexandernst** [comment]
Think about this a little bit more... There should also be a way for me to retrieve the actual warning. A single input field might trigger different warnings (warning messages) depending on the input.

**Comment by joostbaptist** [comment]
Hey Alexander, personally I would recommend using a library such as [yup](https://github.com/jquense/yup) for validation, instead of the validation methods of this package.
